# Generated by Django 5.0.6 on 2024-06-18 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estadocompra',
            name='solicitud',
        ),
    ]
