# Generated by Django 5.0.6 on 2024-06-15 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_departamento_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcompra',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compras.departamento'),
        ),
    ]
